# Generated by Django 4.2 on 2023-05-03 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(max_length=40)),
                ('passport', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('closed', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourist.clients')),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourist.seasons')),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('price', models.IntegerField(max_length=20)),
                ('city', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('info', models.CharField(max_length=120)),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourist.seasons')),
            ],
        ),
    ]
